openapi: "3.1.0"
info:
  title: REST API's RESTfull from 0 with Java, Spring Boot, Kubernetes and Docker
  description: REST API's RESTful from 0 with Java, Spring Boot, Kubernetes and Docker
  version: 1.0.0
  termsOfService: https://pub.erudio.com.br/meus-cursos
  license:
    name: APACHE 2.0
    url: https://pub.erudio.com.br/meus-cursos
servers:
  - url: http://localhost:8080
    description: Development server
tags:
  - name: People
    description: Endpoints for Managing People
  - name: Books
    description: Endpoints for Managing Books
paths:
  /api/person/v1:
    get:
      tags:
        - People
      summary: Find All People
      description: Finds All People
      operationId: findAll
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonDTO'
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - People
      summary: Update a person
      description: Update a person
      operationId: update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/PersonDTO'
          application/yaml:
            schema:
              $ref: '#/components/schemas/PersonDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/PersonDTO'
            application/yaml:
              schema:
                $ref: '#/components/schemas/PersonDTO'
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
    post:
      tags:
        - People
      summary: Create a person
      description: Create a person
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/PersonDTO'
          application/yaml:
            schema:
              $ref: '#/components/schemas/PersonDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/PersonDTO'
            application/yaml:
              schema:
                $ref: '#/components/schemas/PersonDTO'
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
  /api/person/v1/{id}:
    get:
      tags:
        - People
      summary: Finds a person
      description: Find a specific person by your ID
      operationId: findById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/PersonDTO'
            application/yaml:
              schema:
                $ref: '#/components/schemas/PersonDTO'
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - People
      summary: Deleting a person
      description: Deleting a specific person by your ID
      operationId: delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
  /api/book/v1:
    get:
      tags:
        - Books
      summary: Find All Books
      description: Find All Books
      operationId: findAllBooks
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDTO'
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Books
      summary: Update a book
      description: Update a book
      operationId: updateBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/BookDTO'
          application/yaml:
            schema:
              $ref: '#/components/schemas/BookDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/BookDTO'
            application/yaml:
              schema:
                $ref: '#/components/schemas/BookDTO'
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
    post:
      tags:
        - Books
      summary: Create a book
      description: Create a book
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/BookDTO'
          application/yaml:
            schema:
              $ref: '#/components/schemas/BookDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/BookDTO'
            application/yaml:
              schema:
                $ref: '#/components/schemas/BookDTO'
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
  /api/book/v1/{id}:
    get:
      tags:
        - Books
      summary: Finds a book
      description: Find a specific book by your ID
      operationId: findBookById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/BookDTO'
            application/yaml:
              schema:
                $ref: '#/components/schemas/BookDTO'
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Books
      summary: Deleting a book
      description: Deleting a specific book by your ID
      operationId: deleteBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal Server Error
components:
  schemas:
    PersonDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        gender:
          type: string
        _links:
          $ref: '#/components/schemas/Links'
    BookDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        author:
          type: string
        launchDate:
          type: string
          format: date-time
        price:
          type: number
          format: double
        title:
          type: string
        _links:
          $ref: '#/components/schemas/Links'
    Links:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Link'
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
